Formatting markdown files correctly
fsiwi-hka/iwi-website pull request #104
Opened 2022-02-27 10:08 UTC by dustinsommerfeld

Formatting markdown files correctly as specified in the style guide (issue #103).

2022-02-27 12:11 UTC, daniel-vera-g commented
Nice @dustinsommerfeld , which formatter did you use? I know `markdownlint` or `prettier`. As the later can be used for ts too, maybe it would be more beneficial.
I would also add a `lint` or `format` command to the `package.json` to easily run `npm run lint/format` and get the files into the same format. It could also be added to the build stage of the ci/cd to ensure, that the content hast the proper format before deploying/merging.

Ah, and could we add the `.DS_Store` to the `.gitignore` ?

P.S: Can't _review_. properly as I'm not in the orga, maybe should ask to be added 😄

2022-02-27 17:46 UTC, daniel-vera-g requested changes
Siehe mein comment: https://github.com/fsiwi-hka/iwi-website/pull/104#issuecomment-1053536144

2022-02-27 23:43 UTC, mapelpapel approved these changes
While formatting, we could also update / fix some content :)

2022-02-27 23:43 UTC, mapelpapel commented on content/faq/infrastruktur.md
>   - [Übersicht über das gesamte Portfolio](https://www.hs-karlsruhe.de/servicekatalog)
```suggestion
Die Hochschule selbst bietet uns Studierenden verschiedene Dienste wie z.B. Poolräume und verschiedenste Software an. Verantwortlich dafür ist das Rechenzentrum (RZ), auf dessen Website sich verschiedene Übersichten dieser Dienste befinden: https://www.h-ka.de/rz
```
hs-karlsruhe.de is deprecated

2022-02-27 23:43 UTC, mapelpapel commented on content/pages/impressum.md
>  Vertreten durch: Zoe Kammerdiener, Anja Buchmaier
```suggestion
Vertreten durch: Anja Buchmaier, Jens Ettl
```

2022-02-27 23:43 UTC, mapelpapel commented on content/pages/impressum.md
>  Anja Buchmaier
```suggestion
Anja Buchmaier  
Jens Ettl
```

2022-02-28 08:53 UTC, dustinsommerfeld commented
> Nice @dustinsommerfeld , which formatter did you use? I know `markdownlint` or `prettier`. As the later can be used for ts too, maybe it would be more beneficial. I would also add a `lint` or `format` command to the `package.json` to easily run `npm run lint/format` and get the files into the same format. It could also be added to the build stage of the ci/cd to ensure, that the content hast the proper format before deploying/merging.
> 
> Ah, and could we add the `.DS_Store` to the `.gitignore` ?
> 
> ~P.S: Can't _review_. properly as I'm not in the orga, maybe should ask to be added 😄~

Hello @daniel-vera-g,
I don't use any formatting tool, I did it myself.
And the .DS_Store file is created by my macOS :-)

2022-02-28 12:27 UTC, mapelpapel submitted a review, later dismissed

2022-02-28 14:03 UTC, daniel-vera-g approved these changes
Hab die .DS_Store in 1287958d83b8358b850861556e96b7f617ae9944 in die gitignore gepackt @dustinsommerfeld . Jetzt stört Sie in Zukunft nicht.

Wenn du das manuell gemacht hast passt das. Vlt. mache ich mal in Zukunft eine PR für einen markdown formatter oder so.

2022-02-28 21:18 UTC, merged