new sponsor list design + changed sponsor mail address
fsiwi-hka/iwi-website pull request #132
Opened 2022-09-04 21:34 UTC by dustinsommerfeld

Fixed #131

2022-09-04 23:19 UTC, daniel-vera-g requested changes

2022-09-04 23:19 UTC, daniel-vera-g commented on content/pages/unternehmen.md
> +<div id="sponsoren" class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-10 my-10">
Cool gemacht mit css-grid. Was mir beim alten etwas besser gefallen hat, war dass es nicht so viel Platz eingenommen hat 😅 

Interessant wäre so ein [Carousel](https://tailwind-elements.com/docs/standard/components/carousel/) (Müsste man aber selber implementieren oder ne Tailwindcss lib nehmen...)
Was haltet Ihr von einer ausklapbaren Version?
```html
<details class="my-5">
<summary>
<b>Aktuelle Sponsoren Anzeigen</b>
</summary>

... [Sponsoren Logos]...

</details>
```

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/28257108/188337018-20f1cbdd-66c8-49fc-8d0f-e98f453ec883.png">

</br>
Oder mit der Höhe/Breite der Bilder und dem Spacing arbeiten? Da bin ich aber kein Profi 😂

2022-09-04 23:19 UTC, daniel-vera-g commented on content/pages/unternehmen.md
> +<div id="sponsoren" class="grid grid-cols-1 sm:grid-cols-2 gap-10 my-10">
Ich schau mal noch nach nem Satz für Exxeta und über was die Kooperation bei beiden überhaupt geht(Bier & Kaffee) 😉

2022-09-05 21:11 UTC, jwestenhoff reviewed
Passt für mich soweit
Sieht auf Linux auch passend aus

2022-09-06 15:13 UTC, dustinsommerfeld commented on content/pages/unternehmen.md
> +## Unsere aktuellen Hauptsponsoren
Hauptsponsoren werden so auch im Erstiheft seit Jahren erwähnt. Außerdem können Logos von neuen Sponsoren so einfacher hinzugefügt bzw. ehemalige Sponsoren entfernt werden.

2022-09-06 15:15 UTC, dustinsommerfeld commented on content/pages/unternehmen.md
> +<div id="sponsoren" class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-10 my-10">
Ausklappbar ganz cool, aber ich denke, dass die Sponsoren meckern würden, da das Logo nicht direkt sichtbar ist.

Die Logos könnten evtl. noch etwas verkleinert bzw. vergrößert werden, damit alle Logos auf demselben Level sind.

2022-09-06 15:15 UTC, dustinsommerfeld commented on content/pages/unternehmen.md
> +<div id="sponsoren" class="grid grid-cols-1 sm:grid-cols-2 gap-10 my-10">
Das klingt super! Kannst dann direkt hier antworten.

2022-09-24 15:02 UTC, daniel-vera-g approved these changes
Die Anzeige der Sponsoren ist mir im Vergleich zum anderen Content auf der Seite immernoch zu groß aber ok 😄

2022-09-24 15:03 UTC, daniel-vera-g commented on content/pages/unternehmen.md
> +<div id="sponsoren" class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-10 my-10">
Joa, fänd ich nice to have. Kann man sich mal in Zukunft überlegen.

2022-09-25 19:18 UTC, dustinsommerfeld commented
Super vielen Dank fürs drüber schauen! :-) Jaaa ich weiß, aber so ein Bild zu posten ist halt kontra für mobile responsive^^

2022-09-25 19:18 UTC, merged