updated erstiinfos
fsiwi-hka/iwi-website pull request #146
Opened 2022-09-21 20:31 UTC by dustinsommerfeld

@daniel-vera-g Falls du noch etwas finden solltest, sag bescheid :-)

2022-09-21 22:31 UTC, daniel-vera-g requested changes
Bei den Fragezeichen kommt noch was rein oder? 
Ansonsten würde ich: "Wird noch angekündigt" oder so reinschreiben

2022-09-21 22:31 UTC, daniel-vera-g commented on content/pages/erstiinfos.md
> +            <td><strong>???</strong></td>
Was kommt hier rein?

2022-09-22 10:31 UTC, daniel-vera-g commented on content/pages/erstiinfos.md
> +            <td><strong>???</strong></td>
Ok, wenn das noch kommt^^

2022-09-22 10:32 UTC, daniel-vera-g approved these changes
Wenn das mit den Fragezeichen so ok ist, fine for me

2022-09-22 10:32 UTC, dustinsommerfeld commented
Ja erst mal schon. Die Räume sollten noch kommen =)

2022-09-22 10:55 UTC, merged