updated o-phase timetable
fsiwi-hka/iwi-website pull request #152
Opened 2022-09-27 19:59 UTC by dustinsommerfeld

2022-09-27 20:16 UTC, jwestenhoff requested changes

2022-09-27 20:16 UTC, jwestenhoff commented on content/pages/erstiinfos.md
> +              Vorher in Ilias anmelden! Zoom Link in Ilias zu finden.</strong></td>
Der Satz klingt irgendwie komisch

2022-09-27 20:16 UTC, jwestenhoff commented on content/pages/erstiinfos.md
> +              Sponsoren, sind von der Fachschaft IWI und die Erstirucksäcke sind von der AStA / Center of Competence.
```suggestion
              Sponsoren, sind von der Fachschaft IWI und die Erstirucksäcke sind von der AStA / dem Center of Competence.
```

2022-09-27 20:36 UTC, daniel-vera-g commented on content/pages/erstiinfos.md
> +              Vorher in Ilias anmelden! Zoom Link in Ilias zu finden.</strong></td>
Maybe?:
> Weitere Informationen dazu sind **im** [Ilias](https://bit.ly/3E3sm7n) zu finden. Hinweis: Vorher **im** Ilias anmelden **um richtig weitergeleitet zu werden**! **Der** Zoom Link **ist im** Ilias zu finden.

2022-09-27 20:37 UTC, daniel-vera-g approved these changes
Jays Vorschläge noch, dann passt für mich auch

2022-09-27 20:53 UTC, dustinsommerfeld commented on content/pages/erstiinfos.md
> +              Vorher in Ilias anmelden! Zoom Link in Ilias zu finden.</strong></td>
Ja sehr gute Idee. Sorry mein Brain ist mittlerweile erschöpft 😅

2022-09-27 20:57 UTC, dustinsommerfeld reviewed
@jwestenhoff nochmal checken bitte 🤗

2022-09-27 20:57 UTC, dustinsommerfeld commented on content/pages/erstiinfos.md
> +            <td><strong>Weitere Informationen dazu im <a href="https://bit.ly/3E3sm7n">Ilias</a> zu finden. Hinweis:
```suggestion
            <td><strong>Weitere Informationen dazu sind im <a href="https://bit.ly/3E3sm7n">Ilias</a> zu finden. Hinweis: 
```

2022-09-27 20:57 UTC, dustinsommerfeld commented on content/pages/erstiinfos.md
> +              Vorher in Ilias anmelden! Zoom Link in Ilias zu finden.</strong></td>
```suggestion
              Vorher im Ilias anmelden um richtig weitergeleitet zu werden! Der Zoom Link ist im Ilias zu finden.</strong></td>
```

2022-09-27 21:47 UTC, daniel-vera-g approved these changes

2022-09-28 06:20 UTC, jwestenhoff approved these changes

2022-09-28 06:21 UTC, merged