updated sponsors and sorted alphabetically
fsiwi-hka/iwi-website pull request #154
Opened 2022-10-02 11:44 UTC by dustinsommerfeld

2022-10-02 12:13 UTC, daniel-vera-g requested changes
Danke!
Kannst du die Änderungen von #153  hier wieder Rückgängig machen? Das Ändern wir im anderen Branch/PR
Geht einfach mit: `git checkout  master package-lock.json package.json next.config.js` aus dem Sponsoring branch 😄

2022-10-02 12:22 UTC, dustinsommerfeld commented
@daniel-vera-g Kein Ding! 
Sobald ich daheim bin mache ich das Ganze rückgängig ☺️✌️

2022-10-02 16:14 UTC, dustinsommerfeld commented
@daniel-vera-g Erledigt :-)

2022-10-03 08:16 UTC, daniel-vera-g approved these changes

2022-10-03 08:18 UTC, merged