Change Links -> FAQ, Erstiinfos / Change "Wer sind wir?" Site
fsiwi-hka/iwi-website pull request #73
Opened 2021-05-13 08:59 UTC by AnjaB93

Passt das so ;)
Fehlt noch was? 
-> Unternehmen mache ich noch

2021-05-13 09:06 UTC, SimonKienzler requested changes
Neben den konkreten Anmerkungen in den Dateien bitte die DS_Store Dateien aus dem Merge Rquest entfernen, die haben keine Funktion. Die Fotos sind alle wahnsinnig groß, bitte komprimieren. Das erhöht sonst die Ladezeit der Seite extrem.

2021-05-13 09:06 UTC, SimonKienzler commented on content/pages/werwirsind.md
> +  - title: 'Fachbereich Website'
Fachbereich Infrastruktur, oder?

2021-05-13 09:06 UTC, SimonKienzler commented on package-lock.json
>  {
Diese Datei bitte aus dem Commit entfernen, das ist keine inhaltliche Änderung

2021-05-13 09:12 UTC, milbegreif commented on content/pages/werwirsind.md
> +  - title: 'Fachbereich Website'
Joar, sollte man anpassen.

2021-05-13 09:13 UTC, milbegreif commented on package-lock.json
>  {
mir persönlich eig egal, aber würde mich Simon anschließen.

2021-05-13 09:14 UTC, milbegreif commented
Bitte die von Simon angesprochen Punkte anpassen

2021-05-13 09:19 UTC, milbegreif submitted a review, later dismissed
Bitte die von Simon angesprochenen Punkte anpassen.

2021-05-13 11:11 UTC, AnjaB93 commented on content/pages/werwirsind.md
> +  - title: 'Fachbereich Website'
Yes ;)

2021-05-13 11:34 UTC, AnjaB93 commented on package-lock.json
>  {
ich weiß nicht genau wie ich die Datei raus nehme. Ist sie im zweiten Commit raus?

2021-05-13 13:03 UTC, mapelpapel commented on content/pages/unternehmen.md
> +![Kooperation mit Gameforge](/images/unternehmen/exxeta-logo.png)
da steht zwei mal Gameforge

2021-05-13 13:07 UTC, mapelpapel requested changes
Die DS_Store Dateien sollten noch raus und bei den Unternehmen steht 2x Gameforge. Ansonsten passt

2021-05-13 19:57 UTC, SimonKienzler approved these changes

2021-05-13 19:57 UTC, SimonKienzler commented on package-lock.json
>  {
Habs wieder hergestellt

2021-05-14 11:01 UTC, jwestenhoff reviewed
@AnjaB93 
Bitte nächstes Mal Thematisch aufsplitten
(z.B. 1 Branch/Pull Request für "Wer sind wir" und einer für das änderen der Links)

Ist dann übersichtlicher und schneller/einfacher durchzuschauen

2021-05-14 13:26 UTC, mapelpapel commented on content/pages/werwirsind.md
> +      - 'Michael Fischer'
man könnte es ja Alphabetisch anordnen. Und den Manager ganz oben?

2021-05-14 16:06 UTC, AnjaB93 commented on content/pages/unternehmen.md
> +![Kooperation mit Gameforge](/images/unternehmen/exxeta-logo.png)
geändert

2021-05-14 16:06 UTC, AnjaB93 commented on content/pages/werwirsind.md
> +      - 'Michael Fischer'
wie Marcel gesagt hat geändert

2021-05-14 16:12 UTC, jwestenhoff submitted a review, later dismissed

2021-05-14 18:52 UTC, mapelpapel approved these changes

2021-05-14 19:22 UTC, SimonKienzler approved these changes

2021-05-14 19:25 UTC, merged