Implement and style user account menu
fsiwi-hka/iwi-website pull request #79
Opened 2021-08-27 07:33 UTC by SimonKienzler

Because both links were wanted, registration and cloud, I implemented a simple dropdown menu:

![Desktop User Menu](https://user-images.githubusercontent.com/20643018/131089958-c851bd57-8b2e-4843-8678-d873374322a0.png)

On mobile, I kept it as simple as possible:

![Mobile User Menu](https://user-images.githubusercontent.com/20643018/131090029-11b2dbbc-f870-4470-b4ef-f12cdd8fefc8.png)

**Currently blocked** because the menu contains dummy links. Can be merged as soon as the correct links are known. (I however like the links I chose and hope they can stay that way...)

Please test it locally :)

2021-08-27 09:09 UTC, milbegreif submitted a review, later dismissed

2021-08-28 21:09 UTC, mapelpapel commented on components/common/menu.tsx
> +    { title: 'Nextcloud', link: 'https://cloud.iwi-hka.de', icon: faCloud },
We should consider swapping these items, since the registration is only needed once per user
```suggestion
    { title: 'Nextcloud', link: 'https://cloud.iwi-hka.de', icon: faCloud },
    { title: 'Registrierung', link: 'https://registration.iwi-hka.de', icon: faUserPlus },
```

2021-08-28 22:35 UTC, mapelpapel commented on components/common/menu.tsx
> +                    <div className="dropdown-menu top-0 right-0 absolute h-auto flex pt-12 hidden w-[220px]">
As implemented now, the dropdown-menu's padding is blocking the access to the menu-item "Kontakt". But we need a padding between the user icon and the actual dropdown-menu to get it working. My suggested implementation would be a compromise between consistency of opening the dropdown and click-ability of the menu-item "Kontakt". 
It would also be nice, if someone would find a proper solution (if there is one)
```suggestion
                    <div className="dropdown-menu top-0 right-0 absolute h-auto flex pt-7 mt-5 hidden w-[220px]">
```

2021-08-28 22:42 UTC, mapelpapel commented on styles/index.css
When using my menu-item suggestion, we need to add this class to the styles, since it seems not to be available in the standard library.
```suggestion

.pt-7 {
    padding-top: 1.75rem;
}

```

2021-08-28 23:01 UTC, mapelpapel requested changes
We should swap the menu items and fix the issue, that the dropdown-menu is blocking the menu-item "Kontakt".

What I also noticed:
- There is no link preview when hovering the dropdown-items (also no right-click → copy link possible), we should add that
- It would be nice if the menu was centered under the user icon (or at least be more on the right), that would also help with the blocked menu-item problem

2021-08-31 14:27 UTC, SimonKienzler commented on styles/index.css
I'm not in favor of adding custom style classes, this should be a last resort only. Working with 8+4 instead of 7+5 split works as well.

2021-09-08 09:28 UTC, mapelpapel commented
What about this?
> What I also noticed:
> 
> * There is no link preview when hovering the dropdown-items (also no right-click → copy link possible), we should add that
> * It would be nice if the menu was centered under the user icon (or at least be more on the right), that would also help with the blocked menu-item problem

2021-09-17 11:01 UTC, SimonKienzler commented
@mapelpapel 

> There is no link preview when hovering the dropdown-items (also no right-click → copy link possible), we should add that

Fixed

> It would be nice if the menu was centered under the user icon (or at least be more on the right), that would also help with the blocked menu-item problem

This would look weird as the menu would then extend past the overall page margin to the right. I think the solution as-is (with the fixed margin/padding) is enough and doesn't block the "Kontakt" menu item anymore.

2021-09-17 11:51 UTC, mapelpapel approved these changes

2021-11-07 16:42 UTC, milbegreif reviewed
Perfect! is
 ready for deploy

2021-11-07 16:54 UTC, merged